"""Added Foreign Key

Revision ID: cae8d2b4800c
Revises: b350a094b43d
Create Date: 2023-05-14 07:41:59.660145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cae8d2b4800c'
down_revision = 'b350a094b43d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['proster_id'], ['id'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proster_id')

    # ### end Alembic commands ###
